### ISSUE TITLE
Does Not Build on OS X 10.9 Mavericks

### ISSUE THREAD

**Issue by jcsalterego** [jcsalterego/pngpaste#3]
```
cc -Wall -g -O3 -ObjC \
        -framework Foundation -framework AppKit \
        -o pngpaste \
        pngpaste.m
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:68,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:38,
                 from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6,
                 from pngpaste.h:5,
                 from pngpaste.m:5:
/usr/include/MacTypes.h: In function ‘Debugger’:
/usr/include/MacTypes.h:699: error: expected declaration specifiers before ‘__AVAILABILITY_INTERNAL__MAC_10_0_DEP__MAC_10_8’
/usr/include/MacTypes.h:711: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__AVAILABILITY_INTERNAL__MAC_10_0_DEP__MAC_10_8’
/usr/include/MacTypes.h:758: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__AVAILABILITY_INTERNAL__MAC_10_0_DEP__MAC_10_8’
/usr/include/MacTypes.h:770: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__AVAILABILITY_INTERNAL__MAC_10_0_DEP__MAC_10_8’
/usr/include/MacTypes.h:782: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__AVAILABILITY_INTERNAL__MAC_10_0_DEP__MAC_10_8’
/usr/include/MacTypes.h:792: error: expected declaration specifiers before ‘#pragma’
<snip>
In file included from pngpaste.m:5:
pngpaste.h:19: error: expected declaration specifiers before ‘ImageType’
pngpaste.h:23: error: expected specifier-qualifier-list before ‘NSString’
pngpaste.h:27: error: storage class specified for parameter ‘Parameters’
pngpaste.h:33: error: expected declaration specifiers before ‘ImageType’
pngpaste.h:34: error: expected declaration specifiers before ‘NSData’
pngpaste.h:35: error: expected declaration specifiers before ‘NSData’
pngpaste.h:36: error: expected declaration specifiers before ‘NSData’
pngpaste.h:38: error: expected declaration specifiers before ‘Parameters’
pngpaste.h:40: warning: ‘main’ is usually a function
pngpaste.m:9: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
pngpaste.m:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
pngpaste.m:27: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
pngpaste.m:31: error: expected declaration specifiers before ‘ImageType’
pngpaste.m:46: error: expected declaration specifiers before ‘NSData’
pngpaste.m:64: error: expected declaration specifiers before ‘NSData’
pngpaste.m:73: error: expected declaration specifiers before ‘NSData’
pngpaste.m:97: error: expected declaration specifiers before ‘Parameters’
pngpaste.m:138: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
pngpaste.m:170: error: old-style parameter declarations in prototyped function definition
pngpaste.m:170: error: expected ‘{’ at end of input
make: *** [all] Error 1
```
